sudo: required
dist: trusty


os:
- linux

language: php

php:
- '7.1'

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sqlite3 travisTest.db
- ./vendor/laravel/dusk/bin/chromedriver-linux &
- cp .env.travis .env
- php artisan serve > /dev/null 2>&1 &
- composer self-update
- composer install --no-interaction

# - pear install pear/PHP_CodeSniffer
- phpenv rehash
- nvm install 7.7.1
- npm install npm@latest -g
- npm install -g jshint
- npm install



script:
- php artisan dusk
- vendor/bin/phpunit --coverage-text
# - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
- npm run production
#- jshint resources/assets/js/modules/*

